version: '3'
  services:
    frontend:
      image: registry.digitalocean.com/literal/frontend:latest
      restart: unless-stopped
    backend:
      image: registry.digitalocean.com/literal/backend:latest
      restart: unless-stopped
      environment:
        - DATABASE_URL=${DATABASE_URL}
    nginx:
      image: registry.digitalocean.com/literal/nginx:latest
      restart: unless-stopped
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./nginx/certbot/conf:/etc/letsencrypt
        - ./nginx/certbot/www:/var/www/certbot
      command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"''' # Checks every 6h for new ssl certificates
    certbot:
      image: registry.digitalocean.com/literal/certbot:latest
      restart: unless-stopped
      image: certbot/certbot
      volumes:
        - ./nginx/certbot/conf:/etc/letsencrypt
        - ./nginx/certbot/www:/var/www/certbot
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'" # Checks every 12h if ssl cert is expired
  